export const MEDIA_CONSTRAINTS_SET = 'MEDIA_CONSTRAINTS_SET';
export const IS_CHANNEL_READY_SET = 'IS_CHANNEL_READY_SET';
export const IS_INITIATOR_SET = 'IS_INITIATOR_SET';
export const IS_STARTED_SET = 'IS_STARTED_SET';
